apiVersion: v1
kind: ConfigMap
data:
  SCALYR_K8S_CLUSTER_NAME: "YOUR-CLUSTER"

  # Uncomment the line below to use `staging`
  # SCALYR_SERVER: "https://app-logstaging.scalyr.com"

  # disable events and metrics
  SCALYR_K8S_EVENTS_DISABLE: "true"
  SCALYR_REPORT_CONTAINER_METRICS: "false"
  SCALYR_REPORT_K8S_METRICS: "false"

  # settings for high log volume
  SCALYR_MAX_LINE_SIZE: "49900"
  SCALYR_MAX_ALLOWED_REQUEST_SIZE: "5900000"
  SCALYR_PIPELINE_THRESHOLD: "0"
  SCALYR_MIN_REQUEST_SPACING_INTERVAL: "0.1"
  SCALYR_MAX_REQUEST_SPACING_INTERVAL: "3.0"
  SCALYR_MAX_LOG_OFFSET_SIZE: "400000000"
  SCALYR_MAX_EXISTING_LOG_OFFSET_SIZE: "400000000"

  # compression - there's not a huge difference in compressed size between level 3 and 6
  # but there is a non-trivial reduction in CPU usage.
  SCALYR_COMPRESSION_TYPE: "deflate"
  SCALYR_COMPRESSION_LEVEL: "3"

  # K8S cache config
  SCALYR_K8S_QUERY_TIMEOUT_SECS: "120"
  SCALYR_K8S_CACHE_EXPIRY_SECS: "60"

  # profiling information - enable for PoC only
  SCALYR_ENABLE_PROFILING: "true"
  SCALYR_PROFILE_DURATION_MINUTES: "2"
  SCALYR_MAX_PROFILE_INTERVAL_MINUTES: "60"
metadata:
  name: scalyr-config
  namespace: scalyr
  
