apiVersion: v1
kind: ConfigMap
data:
  SCALYR_K8S_CLUSTER_NAME: <your-cluster-name>
  SCALYR_K8S_CACHE_EXPIRY_SECS: "300"
  SCALYR_K8S_CACHE_START_FUZZ_SECS: "15"
  SCALYR_K8S_CACHE_EXPIRY_FUZZ_SECS: "15"
  SCALYR_COMPRESSION_TYPE: bz2
  K8S_EVENTS_DISABLE: "true"
  SCALYR_REPORT_CONTAINER_METRICS: "false"
  SCALYR_REPORT_K8S_METRICS: "false"
  SCALYR_ENABLE_PROFILING: "true"
metadata:
  name: scalyr-config
  namespace: default
