apiVersion: v1
kind: ConfigMap
data:
  SCALYR_K8S_CLUSTER_NAME: <your-cluster-name>
  SCALYR_K8S_CACHE_EXPIRY_SECS: "300"
  SCALYR_COMPRESSION_TYPE: bz2
  K8S_EVENTS_DISABLE: "true"
metadata:
  name: scalyr-config
  namespace: default
