apiVersion: apps/v1
kind: Deployment
metadata:
  name: CUSTOM-APP
spec:
  revisionHistoryLimit: 10
  replicas: XXX
  selector:
    matchLabels:
      app: CUSTOM-APP
  template:
    metadata:
      name: CUSTOM-APP
      labels:
        app: CUSTOM-APP
      annotations:
        # Set a parser for your app
        log.config.scalyr.com/attributes.parser: "loadTestParser"
    spec:
      containers:
      #
      # CONFIGURE YOUR MAIN CONTAINER HERE
      #
      - name: MAIN-CONTAINER
        image: MAIN-CONTAINER-IMAGE:VERSION
        imagePullPolicy: IfNotPresent
        # Other fields here as necessary
      #
      # END OF MAIN CONTAINER
      #

      # 
      # SIDECAR SCALYR AGENT
      #
      - env:
        - name: SCALYR_API_KEY
          valueFrom:
            secretKeyRef:
              key: scalyr-api-key
              name: scalyr-api-key
        - name: SCALYR_K8S_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: SCALYR_K8S_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: SCALYR_K8S_POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: SCALYR_K8S_POD_UID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.uid
        - name: SCALYR_K8S_KUBELET_HOST_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        envFrom:
        - configMapRef:
            name: scalyr-config
        image: scalyr/scalyr-k8s-agent:2.1.1
        imagePullPolicy: Always
        name: scalyr-agent
        resources:
          limits:
            memory: 150Mi
          requests:
            memory: 80Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/docker/containers
          name: varlibdockercontainers
          readOnly: true
        - mountPath: /var/log/pods
          name: varlogpods
          readOnly: true
        - mountPath: /var/log/containers
          name: varlogcontainers
          readOnly: true
        - mountPath: /var/scalyr/docker.sock
          name: dockersock
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      # SERVICE ACCOUNT
      # service account needs to be the scalyr-service-account, OR
      # your own service account with the same permissions as the
      # scalyr-service-account
      serviceAccount: scalyr-service-account
      serviceAccountName: scalyr-service-account
      terminationGracePeriodSeconds: 30
      #
      # SIDECAR SCALYR AGENT NEEDS THESE HOST PATHS MAPPED
      #
      volumes:
      - hostPath:
          path: /var/lib/docker/containers
          type: ""
        name: varlibdockercontainers
      - hostPath:
          path: /var/log/pods
          type: ""
        name: varlogpods
      - hostPath:
          path: /var/log/containers
          type: ""
        name: varlogcontainers
      - hostPath:
          path: /var/run/docker.sock
          type: ""
        name: dockersock

