apiVersion: apps/v1
kind: Deployment
metadata:
  name: CUSTOM-APP
spec:
  replicas: XXX
  selector:
    matchLabels:
      app: CUSTOM-APP
  template:
    metadata:
      name: CUSTOM-APP
      labels:
        app: CUSTOM-APP
      annotations:
        # Set a parser for your app
        log.config.scalyr.com/attributes.parser: "customParser"
    spec:
      # SERVICE ACCOUNT
      # service account needs to be the scalyr-service-account, OR
      # your own service account with the same permissions as the
      # scalyr-service-account
      serviceAccountName: scalyr-service-account

      containers:
      #
      # CONFIGURE YOUR MAIN CONTAINER HERE
      #
      - name: MAIN-CONTAINER
        image: MAIN-CONTAINER-IMAGE:VERSION
        imagePullPolicy: IfNotPresent
        # Other fields here as necessary
      #
      # END OF MAIN CONTAINER
      #

      # 
      # SIDECAR SCALYR AGENT
      #
      - name: scalyr-agent
        image: scalyr/scalyr-k8s-agent:2.0.54.sidecar_mode.1
        imagePullPolicy: Always
        env:
          - name: SCALYR_API_KEY
            valueFrom:
              secretKeyRef:
                name: scalyr-api-key
                key: scalyr-api-key
          - name: SCALYR_K8S_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: SCALYR_K8S_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: SCALYR_K8S_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: SCALYR_K8S_POD_UID
            valueFrom:
              fieldRef:
                fieldPath: metadata.uid
          - name: SCALYR_K8S_KUBELET_HOST_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
        envFrom:
          - configMapRef:
              name: scalyr-config
        resources:
          limits:
            memory: 150Mi
          requests:
            memory: 60Mi
        volumeMounts:
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: varlogpods
          mountPath: /var/log/pods
          readOnly: true
        - name: varlogcontainers
          mountPath: /var/log/containers
          readOnly: true
        - name: dockersock
          mountPath: /var/scalyr/docker.sock
      #
      # SIDECAR SCALYR AGENT NEEDS THESE HOST PATHS MAPPED
      #
      volumes:
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: varlogpods
        hostPath:
          path: /var/log/pods
      - name: varlogcontainers
        hostPath:
          path: /var/log/containers
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock

